const defaultCookies = {
  checklistGenFilter: "All",
  travelFilter: "transport",
  planeFilter: "plane",
  collectionSelect: "Pokéballs",
  collectionUserSelect: "All",
  displayAnimatedSpritesPreGen8: true,
  displayAnimatedSpritesPostGen8: false,
  displayEvolutionSprites: true,
  displayGameSprites: true,
  displayMapOnGent: false,
  displayCounterRanking: "rankingEnc",
  filterCounterDate: [],
  filterCounterGame: [],
  filterCounterGen: [],
  filterCounterMethod: [],
  filterCounterPokedexNrLower: "",
  filterCounterPokedexNrUpper: "",
  filterCounterTrainer: [],
  filterEvolutions: false,
  filterGroups: false,
  filterShinyDate: [],
  filterShinyGame: [],
  filterShinyGen: [],
  filterShinyMethod: [],
  filterShinyPokedexNrLower: "",
  filterShinyPokedexNrUpper: "",
  filterShinyTrainer: [],
  sortCountersCompleted: "newest",
  sortCountersOngoing: "newest",
  sortShiny: "newest",
  theme: "dark",
};

const defaultCookiesList = Object.keys(defaultCookies);

export { defaultCookies, defaultCookiesList };
